name: Terraform CI/CD

on:
  push:
    branches:
      - feature/terrform_poc2
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Lint, Security Check, and Deploy'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Terraform Init'
      run: |
          cd poc1 
          terraform init

    - name: 'Terraform Format'
      run: |
           cd poc1
           terraform fmt

    - name: 'Terraform Validate'
      run: |
           cd poc1
           terraform validate

    - name: 'Terraform Plan'
      run: |
          cd poc1
          terraform plan -out=tfplan

    - name: 'Terraform Apply'
      run: |
          cd poc1 
          terraform apply -auto-approve tfplan